version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - build:
          context:
            - NPM
jobs:
  build:
    environment:
      - DATABASE_URL: postgres://ubuntu:@127.0.0.1:5432/circle_test
    working_directory: ~/package
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Deploy Package
          command: |
            yarn
            yarn build
            echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
            npm publish
