version: 2
jobs:
  build:
    environment:
      - DATABASE_URL: postgres://ubuntu:@127.0.0.1:5432/circle_test
    working_directory: ~/package
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Deploy Package
          command: |
            npm install npm-cli-login
            yarn
            yarn build
            npm run login
            npm run 2npm
